version: 2.1

executors:
  client_node:
    working_directory: /tmp/ingred_ui
    docker:
      - image: circleci/node:12.13.0
commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore yarn dependencies
          keys:
            - yarn-cache-v0-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v0-{{ .Branch }}-
            - yarn-cache-v0-

  save_yarn:
    steps:
      - save_cache:
          name: Cache yarn dependencies
          key: yarn-cache-v0-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  publish:
    parameters:
      semver:
        type: string
    steps:
      - run:
          name: publish
          command: make -f ci.mk publish SEMVER=<< parameters.semver >>

jobs:
  test:
    executor: client_node
    steps:
      - checkout
      - restore_yarn
      - run:
          name: yarn install
          command: make -f ci.mk install
      - run:
          name: test
          command: make -f ci.mk test
      - save_yarn
  publish:
    parameters:
      semver:
        type: enum
        enum: ["patch", "minor", "major"]
    executor: client_node
    steps:
      - checkout
      - restore_yarn
      - run:
          name: yarn install
          command: make -f ci.mk install
      - run: git config --global user.email ingred-ui@voyagegroup.com
      - run: git config --global user.name CircleCI
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - publish:
          semver: << parameters.semver >>

workflows:
  test:
    jobs:
      - test
  publish:
    jobs:
      - 0.0.X_patch_publish_approval:
          type: approval
          filters: { branches: { only: feature-ci } }
      - 0.X.0_minor_publish_approval:
          type: approval
          filters: { branches: { only: feature-ci } }
      - X.0.0_major_publish_approval:
          type: approval
          filters: { branches: { only: feature-ci } }
      - publish:
          name: patch_publish
          semver: patch
          requires:
            - 0.0.X_patch_publish_approval
          filters: { branches: { only: feature-ci } }
      - publish:
          name: minor_publish
          semver: minor
          requires:
            - 0.X.0_minor_publish_approval
          filters: { branches: { only: feature-ci } }
      - publish:
          name: major_publish
          semver: major
          requires:
            - X.0.0_major_publish_approval
          filters: { branches: { only: feature-ci } }
